import Menu from "./componentes/Menu.js"
import Footer from "./componentes/Footer.js"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 //o page.js é construido como filho da página
export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body style={{margin: 0}}>
        <Menu/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}